// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countUsersByIP = `-- name: CountUsersByIP :one
SELECT COUNT(*) FROM users
WHERE ip = ?
`

func (q *Queries) CountUsersByIP(ctx context.Context, ip string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByIP, ip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, session_token, created_at, expires_at)
VALUES (?, ?, datetime('now'), ?)
RETURNING id, user_id, session_token, created_at, expires_at
`

type CreateSessionParams struct {
	UserID       int64
	SessionToken string
	ExpiresAt    time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.SessionToken, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, created_at)
VALUES (?, ?, datetime('now'))
RETURNING id, username, password_hash, created_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

type CreateUserRow struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const createUserWithIP = `-- name: CreateUserWithIP :one
INSERT INTO users (username, password_hash, ip, created_at)
VALUES (?, ?, ?, datetime('now'))
RETURNING id, username, password_hash, created_at
`

type CreateUserWithIPParams struct {
	Username     string
	PasswordHash string
	Ip           string
}

type CreateUserWithIPRow struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
}

func (q *Queries) CreateUserWithIP(ctx context.Context, arg CreateUserWithIPParams) (CreateUserWithIPRow, error) {
	row := q.db.QueryRowContext(ctx, createUserWithIP, arg.Username, arg.PasswordHash, arg.Ip)
	var i CreateUserWithIPRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions WHERE session_token = ?
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, sessionToken string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByToken, sessionToken)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, session_token, created_at, expires_at
FROM sessions
WHERE session_token = ?
LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, sessionToken string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, sessionToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, created_at
FROM users
WHERE id = ?
LIMIT 1
`

type GetUserByIDRow struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at
FROM users
WHERE username = ?
LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
